# See: https://docs.github.com/en/actions/creating-actions
name: Gem Push
author: FreeAgent
branding:
  icon: 'globe'
  color: 'red'
description: Push gem packages to a rubygems compatible repository
inputs:
  key:
    description: "Name of credentials key to use from ~/.gem/credentials."
    default: ""
  gem-glob:
    description: File glob to match the .gem files to push
    default: "pkg/*.gem"
  pre-release:
    description: Whether to push pre-release versions, instead of release versions (the default).
    default: false
  tag:
    description: After pushing a new gem version, git tag with the version string
    default: true
  working-directory:
    description: "The working directory of the ruby project. Useful for cases where files like .ruby-version and Gemfile aren't located in the root directory."
    required: false
    default: "."
outputs:
  pushed-version:
    description: "The version of the gem pushed to the repository"
    value: ${{ steps.push-gem.outputs.pushed-version }}

runs:
  using: "composite"
  steps:
    - name: Push Gem
      id: push-gem
      shell: bash
      run: |
        PATH="${{ github.action_path }}:$PATH"
        args=""
        [ '${{ inputs.pre-release }}' == true ] && args="$args -p"
        [ '${{ inputs.tag }}' == true ] && args="$args -t"
        [ ! -z ${{ inputs.working-directory }} ] && cd ${{ inputs.working-directory }}
        gem-push-action.sh -k "${{inputs.key}}" $args ${{inputs.gem-glob}}
